In [2]:
import pandas as pd

df = pd.read_csv('../data/processed/sample_data.csv')

df.head()

C:\Users\A\AppData\Local\Temp\ipykernel_4948\971669319.py:3: DtypeWarning: Columns (0: id) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/processed/sample_data.csv')

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,39651438,NaN,32000.0,32000.0,32000.0,60 months,10.49,687.65,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,16411620,NaN,9600.0,9600.0,9600.0,36 months,12.99,323.42,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,45122316,NaN,4000.0,4000.0,4000.0,36 months,6.68,122.93,A,A3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,125356772,NaN,6025.0,6025.0,6025.0,36 months,10.91,197.00,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,128490686,NaN,25000.0,25000.0,25000.0,60 months,26.30,752.96,E,E5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns.tolist()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'last_fico_range_high',
 'last_fico_range_low',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

:

In [ ]:
df.head(1)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,39651438,NaN,32000.0,32000.0,32000.0,60 months,10.49,687.65,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

:

Let us analyse all the columns and group them based on relevant categories. By this we can group our data as per relevance.

Category 1: User specific personal data (Borrower's information)

'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc'


 | Column                | Meaning                 |
| --------------------- | ----------------------- |
| `annual_inc`          | Annual income           |
| `emp_length`          | Employment duration     |
| `home_ownership`      | Own / Rent / Mortgage   |
| `verification_status` | Income verified or not  |
| `addr_state`          | State                   |
| `zip_code`            | Area (first 3 digits)   |
| `title`               | Loan title (user given) |
| `purpose`             | Reason for loan         |

Category 2: Loan related data (Loan Information)

'loan_amnt'
'term'
'int_rate'
'installment'

| Column            | Meaning                      |
| ----------------- | ---------------------------- |
| `loan_amnt`       | Requested loan amount        |
| `funded_amnt`     | Total funded amount          |
| `funded_amnt_inv` | Investor-funded amount       |
| `term`            | Loan duration (36/60 months) |
| `int_rate`        | Interest rate                |
| `installment`     | Monthly payment              |
| `grade`           | Risk grade (A–G)             |
| `sub_grade`       | More granular grade          |
| `pymnt_plan`      | Payment plan indicator       |

Category 3: Past Credit History (Background Check) 

| Column                       | Meaning                          |
| ---------------------------- | -------------------------------- |
| `dti`                        | Debt-to-income ratio             |
| `delinq_2yrs`                | Delinquencies in last 2 years    |
| `inq_last_6mths`             | Credit inquiries (6 months)      |
| `open_acc`                   | Open credit accounts             |
| `total_acc`                  | Total accounts                   |
| `revol_bal`                  | Revolving balance                |
| `revol_util`                 | Credit utilization (%)           |
| `pub_rec`                    | Public records (bankruptcy etc.) |
| `collections_12_mths_ex_med` | Collections (excluding medical)  |
| `acc_now_delinq`             | Accounts currently delinquent    |

Category 4: If the person will repay the loan or not (Target Vairbale)

| Column        | Meaning                                     |
| ------------- | ------------------------------------------- |
| `loan_status` | Loan result (Fully Paid, Charged Off, etc.) |

Category 5: Redundant Variables + Data Leak (Info which is not present at the time of giving loan but received later on. (Not useful for model))

'id',
 'member_id'
'funded_amnt',
 'funded_amnt_inv',

 | Column                    | Meaning                         |
| ------------------------- | ------------------------------- |
| `total_pymnt`             | Total payment received          |
| `total_pymnt_inv`         | Payment received from investors |
| `total_rec_prncp`         | Principal repaid                |
| `total_rec_int`           | Interest received               |
| `total_rec_late_fee`      | Late fees                       |
| `recoveries`              | Amount recovered after default  |
| `collection_recovery_fee` | Fees for recovery               |
| `last_pymnt_d`            | Last payment date               |
| `last_pymnt_amnt`         | Last payment amount             |

Category 6: Credit Limt Utilisation

| Column              | Meaning                     |
| ------------------- | --------------------------- |
| `tot_cur_bal`       | Total current balance       |
| `total_bal_ex_mort` | Balance excluding mortgage  |
| `total_bc_limit`    | Credit card limit           |
| `avg_cur_bal`       | Average balance per account |

Category 7: Timeline

| Column               | Meaning           |
| -------------------- | ----------------- |
| `issue_d`            | Loan issue date   |
| `earliest_cr_line`   | First credit line |
| `last_credit_pull_d` | Last credit check |

Category 8: Derived infos

| Column                 | Meaning                   |
| ---------------------- | ------------------------- |
| `policy_code`          | Internal policy           |
| `application_type`     | Individual / Joint        |
| `hardship_flag`        | Hardship status           |
| `debt_settlement_flag` | Debt settlement indicator |

:

Lets analyse the columns depending on priority/usefulness

dti = debt to income ratio  
higher = risky borrower

In [ ]:
# Step A — Understand the TYPE
# Is it:

# Numeric (int/float)
# Categorical (object)
df['dti'].dtype

dtype('float64')

:

In [ ]:
# Step B — Look at Values
# df['column_name'].head()

# 👉 Just see what it looks like
df['dti'].head()

0    24.05
1    10.03
2    19.53
3     9.16
4    36.26
Name: dti, dtype: float64

:

In [ ]:
# Step C — Summary Stats
# For numeric:
# df['column_name'].describe()

# 👉 Check:

# mean
# min / max
# outliers
# For categorical:
# df['column_name'].value_counts()

# 👉 Check:

# categories
# imbalance
df['dti'].describe()

count    99916.000000
mean        18.854423
std         14.196784
min          0.000000
25%         11.870000
50%         17.890000
75%         24.530000
max        999.000000
Name: dti, dtype: float64

:

:

In [ ]:
# Step D — Missing Values
# df['column_name'].isnull().sum()

# 👉 Important:

# Too many missing? → may drop later
df['dti'].isnull().sum()

np.int64(84)

:

In [ ]:
# Step E — MOST IMPORTANT → Relationship with TARGET
# df.groupby('target')['column_name'].mean()

# OR

# df.groupby('column_name')['target'].mean()

# 👉 This tells:

# “Does this column actually affect default?”
df.groupby('loan_status')['dti'].mean()

loan_status
Charged Off                                            20.190192
Current                                                19.682505
Does not meet the credit policy. Status:Charged Off    13.675484
Does not meet the credit policy. Status:Fully Paid     14.081667
Fully Paid                                             17.808166
In Grace Period                                        20.783451
Late (16-30 days)                                      18.509679
Late (31-120 days)                                     20.115155
Name: dti, dtype: float64

:

In [ ]:
#df.groupby('dti')['loan_status'].head()

:

Column: dti  
Type: Numeric  
Missing: Low  
Insight: Higher DTI → higher default risk

In [ ]:
# Analyze these columns:

# annual_inc
# dti
# loan_amnt
# int_rate
# emp_length
# home_ownership
# verification_status
# revol_util

:

In [ ]:
df['annual_inc'].dtype

dtype('float64')

:

In [ ]:
df['annual_inc'].head()

0    120000.0
1     21900.0
2     83000.0
3     52000.0
4     65000.0
Name: annual_inc, dtype: float64

:

In [ ]:
df['annual_inc'].describe()

count    9.999600e+04
mean     7.805917e+04
std      8.133376e+04
min      0.000000e+00
25%      4.600000e+04
50%      6.500000e+04
75%      9.300000e+04
max      1.099920e+07
Name: annual_inc, dtype: float64

:

In [ ]:
df['annual_inc'].isnull().sum()

np.int64(4)

:

In [ ]:
df.groupby('loan_status')['annual_inc'].mean()

loan_status
Charged Off                                            70829.915312
Current                                                80703.867900
Does not meet the credit policy. Status:Charged Off    68999.594194
Does not meet the credit policy. Status:Fully Paid     66362.776667
Fully Paid                                             77749.417079
In Grace Period                                        79967.818288
Late (16-30 days)                                      83646.050642
Late (31-120 days)                                     76086.984912
Name: annual_inc, dtype: float64

:

Column: annual_inc  
Type: Numeric  
Missing: Low  
Insight:   Lower income -> More chances of default

Inspecting Target:

In [ ]:
df['loan_status'].value_counts()

loan_status
Fully Paid                                             47460
Current                                                38887
Charged Off                                            12034
Late (31-120 days)                                       969
In Grace Period                                          368
Late (16-30 days)                                        187
Does not meet the credit policy. Status:Fully Paid        60
Does not meet the credit policy. Status:Charged Off       31
Name: count, dtype: int64

:

| Status          | Meaning                      |
| --------------- | ---------------------------- |
| Fully Paid      | Loan repaid successfully     |
| Charged Off     | Loan defaulted (written off) |
| Default         | Defaulted                    |
| Current         | Still ongoing                |
| Late            | Payment delayed              |
| In Grace Period | Temporary delay              |

✅ Keep ONLY:

Fully Paid → Good (0)
Charged Off → Bad (1)

❌ Remove:

Current (unknown outcome)
Late (uncertain)
In Grace Period (temporary)

In [ ]:
df = df[df['loan_status'].isin(['Fully Paid', 'Charged Off'])]

:

In [ ]:
df['target'] = df['loan_status'].apply(lambda x: 1 if x == 'Charged Off' else 0)

C:\Users\A\AppData\Local\Temp\ipykernel_11592\627173182.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['target'] = df['loan_status'].apply(lambda x: 1 if x == 'Charged Off' else 0)

:

In [ ]:
df['target'].value_counts()

target
0    47460
1    12034
Name: count, dtype: int64

:

In [ ]:
df['target'].value_counts(normalize=True)

target
0    0.797728
1    0.202272
Name: proportion, dtype: float64

:

In [ ]:
# Target Variable Definition:

# - 0 → Fully Paid (Non-default)
# - 1 → Charged Off (Default)

# Removed:
# - Current
# - Late
# - In Grace Period

# Reason:
# Only clear outcomes should be used for supervised learning

:

In [ ]:
df.groupby('target')['loan_amnt'].mean()

target
0    14076.795723
1    15667.178411
Name: loan_amnt, dtype: float64

:

In [ ]:
df.groupby('target')['int_rate'].mean()

target
0    12.674815
1    15.773765
Name: int_rate, dtype: float64

:

In [ ]:
df.groupby('target')['dti'].mean()

target
0    17.808166
1    20.190192
Name: dti, dtype: float64

:

In [ ]:
# Expectation:
# Defaults → higher interest
# Defaults → higher DTI

# 👉 If this trend appears → data is consistent ✅

:

In [ ]:
df.to_csv('../data/processed/cleaned_data.csv', index=False)

:

Next Step: Feature Selection (Keep vs Drop)

Core Principle (REMEMBER THIS)

👉 Use only pre-loan information

❌ Drop anything that happens after loan is given

In [ ]:
# Step 1 — Identify Leakage Columns (DROP ❌)

# These columns leak future information:

# ❌ Drop immediately:
cols_to_drop = [
    'funded_amnt',
    'funded_amnt_inv',
    'total_pymnt',
    'total_pymnt_inv',
    'total_rec_prncp',
    'total_rec_int',
    'total_rec_late_fee',
    'recoveries',
    'collection_recovery_fee',
    'last_pymnt_d',
    'last_pymnt_amnt'
]

df.drop(columns=cols_to_drop, inplace=True, errors='ignore')
# 🧠 Why drop?

# 👉 Example:

# total_pymnt = total money received
# If loan defaulted → low payment

# 👉 Using this = cheating ❌ (data leakage)

:

In [ ]:
# Step 2 — Drop Irrelevant Columns

# These don’t help prediction:

cols_to_drop += [
    'id',
    'member_id',
    'url',
    'zip_code',
    'title',
    'policy_code'
]

df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

:

In [ ]:
# Step 3 — Drop High Missing Columns

# Run:

missing = df.isnull().mean().sort_values(ascending=False)
missing.head(20)

next_pymnt_d                                  1.000000
orig_projected_additional_accrued_interest    0.997378
hardship_amount                               0.995848
hardship_last_payment_amount                  0.995848
hardship_length                               0.995848
hardship_status                               0.995848
hardship_reason                               0.995848
payment_plan_start_date                       0.995848
hardship_dpd                                  0.995848
hardship_payoff_balance_amount                0.995848
hardship_loan_status                          0.995848
hardship_type                                 0.995848
hardship_end_date                             0.995848
hardship_start_date                           0.995848
deferral_term                                 0.995848
sec_app_mths_since_last_major_derog           0.994974
sec_app_revol_util                            0.986402
sec_app_open_acc                              0.986083
sec_app_num_rev_accts                         0.986083
revol_bal_joint                               0.986083
dtype: float64

:

In [ ]:
# 👉 Then drop columns with >50% missing:

cols_to_drop = missing[missing > 0.5].index
df.drop(columns=cols_to_drop, inplace=True)

:

Step 4 — Keep Important Features (CORE FEATURES 🔥)

These are your strong predictors:

💰 Financial
annual_inc
dti

💳 Credit Behavior
revol_util
delinq_2yrs
total_acc

📊 Loan Info
loan_amnt
int_rate
term

👤 Stability
emp_length
home_ownership
verification_status

🎯 Risk Score
grade

In [ ]:
df.columns

Index(['loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'purpose', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv',
       'last_credit_pull_d', 'last_fico_range_high', 'last_fico_range_low',
       'collections_12_mths_ex_med', 'application_type', 'acc_now_delinq',
       'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'disbursement_method',
       'debt_settlement_flag', 'target'],
      dtype='str')

:

In [ ]:
df.shape

NameError: name 'df' is not defined

:

Feature Selection:

- Dropped leakage columns (post-loan data)
- Dropped irrelevant identifiers
- Dropped high-missing columns
- Retained pre-loan features only

In [ ]:
df.to_csv('../data/processed/final_data.csv', index=False)

:

In [ ]:
df.head(3)

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,target
1,9600.0,36 months,12.99,323.42,C,C1,NaN,NaN,RENT,21900.0,...,1.0,0.0,11600.0,4509.0,2400.0,0.0,N,Cash,N,0
2,4000.0,36 months,6.68,122.93,A,A3,System Analyst,4 years,MORTGAGE,83000.0,...,0.0,0.0,222616.0,64253.0,5600.0,76154.0,N,Cash,N,0
3,6025.0,36 months,10.91,197.00,B,B4,Admin assistant,10+ years,RENT,52000.0,...,0.0,0.0,32227.0,5559.0,11000.0,11127.0,N,Cash,N,0

:

: