In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/final_data.csv")  # put correct path

df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,target
0,9600.0,36 months,12.99,323.42,C,C1,NaN,NaN,RENT,21900.0,...,1.0,0.0,11600.0,4509.0,2400.0,0.0,N,Cash,N,0
1,4000.0,36 months,6.68,122.93,A,A3,System Analyst,4 years,MORTGAGE,83000.0,...,0.0,0.0,222616.0,64253.0,5600.0,76154.0,N,Cash,N,0
2,6025.0,36 months,10.91,197.00,B,B4,Admin assistant,10+ years,RENT,52000.0,...,0.0,0.0,32227.0,5559.0,11000.0,11127.0,N,Cash,N,0
3,20000.0,36 months,9.49,640.57,B,B2,Manager,10+ years,MORTGAGE,100000.0,...,0.0,0.0,322295.0,33695.0,23900.0,29995.0,N,Cash,N,0
4,1000.0,36 months,8.18,31.42,B,B1,NaN,NaN,RENT,23000.0,...,0.0,0.0,9979.0,7252.0,1700.0,5779.0,N,Cash,N,0

In [11]:
# missing = df.isnull().mean().sort_values(ascending=False)
# missing.head(2)

In [8]:
# a = df.isnull().mean().sort_values(ascending=False)
# a.head(5)

In [9]:
print(df.shape)
print(df.columns)

(59494, 78)
Index(['loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'purpose', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv',
       'last_credit_pull_d', 'last_fico_range_high', 'last_fico_range_low',
       'collections_12_mths_ex_med', 'application_type', 'acc_now_delinq',
       'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'disbursement_method',
       'debt_settlement_flag', 'target'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 59494 entries, 0 to 59493
Data columns (total 78 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   59494 non-null  float64
 1   term                        59494 non-null  str
 2   int_rate                    59494 non-null  float64
 3   installment                 59494 non-null  float64
 4   grade                       59494 non-null  str
 5   sub_grade                   59494 non-null  str
 6   emp_title                   55660 non-null  str
 7   emp_length                  56024 non-null  str
 8   home_ownership              59494 non-null  str
 9   annual_inc                  59494 non-null  float64
 10  verification_status         59494 non-null  str
 11  issue_d                     59494 non-null  str
 12  loan_status                 59494 non-null  str
 13  pymnt_plan                  59494 non-null  str
 14  purpose                     59494 non-null  str
 15  addr_state                  59494 non-null  str
 16  dti                         59474 non-null  float64
 17  delinq_2yrs                 59494 non-null  float64
 18  earliest_cr_line            59494 non-null  str
 19  fico_range_low              59494 non-null  float64
 20  fico_range_high             59494 non-null  float64
 21  inq_last_6mths              59494 non-null  float64
 22  open_acc                    59494 non-null  float64
 23  pub_rec                     59494 non-null  float64
 24  revol_bal                   59494 non-null  float64
 25  revol_util                  59462 non-null  float64
 26  total_acc                   59494 non-null  float64
 27  initial_list_status         59494 non-null  str
 28  out_prncp                   59494 non-null  float64
 29  out_prncp_inv               59494 non-null  float64
 30  last_credit_pull_d          59493 non-null  str
 31  last_fico_range_high        59494 non-null  float64
 32  last_fico_range_low         59494 non-null  float64
 33  collections_12_mths_ex_med  59492 non-null  float64
 34  application_type            59494 non-null  str
 35  acc_now_delinq              59494 non-null  float64
 36  tot_coll_amt                56604 non-null  float64
 37  tot_cur_bal                 56604 non-null  float64
 38  total_rev_hi_lim            56604 non-null  float64
 39  acc_open_past_24mths        57467 non-null  float64
 40  avg_cur_bal                 56604 non-null  float64
 41  bc_open_to_buy              56847 non-null  float64
 42  bc_util                     56821 non-null  float64
 43  chargeoff_within_12_mths    59492 non-null  float64
 44  delinq_amnt                 59494 non-null  float64
 45  mo_sin_old_il_acct          54959 non-null  float64
 46  mo_sin_old_rev_tl_op        56604 non-null  float64
 47  mo_sin_rcnt_rev_tl_op       56604 non-null  float64
 48  mo_sin_rcnt_tl              56604 non-null  float64
 49  mort_acc                    57467 non-null  float64
 50  mths_since_recent_bc        56886 non-null  float64
 51  mths_since_recent_inq       51902 non-null  float64
 52  num_accts_ever_120_pd       56604 non-null  float64
 53  num_actv_bc_tl              56604 non-null  float64
 54  num_actv_rev_tl             56604 non-null  float64
 55  num_bc_sats                 57109 non-null  float64
 56  num_bc_tl                   56604 non-null  float64
 57  num_il_tl                   56604 non-null  float64
 58  num_op_rev_tl               56604 non-null  float64
 59  num_rev_accts               56604 non-null  float64
 60  num_rev_tl_bal_gt_0         56604 non-null  float64
 61  num_sats                    57109 non-null  float64
 62  num_tl_120dpd_2m            54324 non-null  float64
 63  num_tl_30dpd                56604 non-null  float64
 64  num_tl_90g_dpd_24m          56604 non-null  float64
 65  num_tl_op_past_12m          56604 non-null  float64
 66  pct_tl_nvr_dlq              56599 non-null  float64
 67  percent_bc_gt_75            56827 non-null  float64
 68  pub_rec_bankruptcies        59463 non-null  float64
 69  tax_liens                   59493 non-null  float64
 70  tot_hi_cred_lim             56604 non-null  float64
 71  total_bal_ex_mort           57467 non-null  float64
 72  total_bc_limit              57467 non-null  float64
 73  total_il_high_credit_limit  56604 non-null  float64
 74  hardship_flag               59494 non-null  str
 75  disbursement_method         59494 non-null  str
 76  debt_settlement_flag        59494 non-null  str
 77  target                      59494 non-null  int64
dtypes: float64(58), int64(1), str(19)
memory usage: 35.4 MB

In [28]:
df.shape

(59494, 79)

What to Analyze

Now go column by column mentally:

1. Numerical (int, float)
Example: loan_amnt, annual_inc
👉 These go into ML directly
2. Categorical (object)
Example: home_ownership, grade
👉 Need encoding later
3. Dates
Example: issue_d
👉 Very important for time-based features
⚠️ Important Insight

If numbers are stored as object → bad data quality
(e.g. "10 years" instead of 10)

✅ Your Goal Here

Understand:

Which columns are numeric
Which need conversion

In [12]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)

missing_percentage = (missing / len(df)) * 100

pd.DataFrame({
    "Missing Count": missing,
    "Missing %": missing_percentage
})

                            Missing Count  Missing %
mths_since_recent_inq                7592  12.760951
num_tl_120dpd_2m                     5170   8.689952
mo_sin_old_il_acct                   4535   7.622617
emp_title                            3834   6.444347
emp_length                           3470   5.832521
pct_tl_nvr_dlq                       2895   4.866037
num_actv_rev_tl                      2890   4.857633
total_rev_hi_lim                     2890   4.857633
avg_cur_bal                          2890   4.857633
tot_cur_bal                          2890   4.857633
tot_coll_amt                         2890   4.857633
total_il_high_credit_limit           2890   4.857633
tot_hi_cred_lim                      2890   4.857633
num_tl_op_past_12m                   2890   4.857633
num_rev_accts                        2890   4.857633
num_op_rev_tl                        2890   4.857633
num_actv_bc_tl                       2890   4.857633
mo_sin_rcnt_rev_tl_op                2890   4.857633
mo_sin_rcnt_tl                       2890   4.857633
num_il_tl                            2890   4.857633
num_bc_tl                            2890   4.857633
num_tl_30dpd                         2890   4.857633
num_tl_90g_dpd_24m                   2890   4.857633
num_accts_ever_120_pd                2890   4.857633
num_rev_tl_bal_gt_0                  2890   4.857633
mo_sin_old_rev_tl_op                 2890   4.857633
bc_util                              2673   4.492890
percent_bc_gt_75                     2667   4.482805
bc_open_to_buy                       2647   4.449188
mths_since_recent_bc                 2608   4.383635
num_bc_sats                          2385   4.008808
num_sats                             2385   4.008808
acc_open_past_24mths                 2027   3.407066
total_bal_ex_mort                    2027   3.407066
mort_acc                             2027   3.407066
total_bc_limit                       2027   3.407066
revol_util                             32   0.053787
pub_rec_bankruptcies                   31   0.052106
dti                                    20   0.033617
chargeoff_within_12_mths                2   0.003362
collections_12_mths_ex_med              2   0.003362
last_credit_pull_d                      1   0.001681
tax_liens                               1   0.001681

In [23]:
# df1 = pd.read_csv('../data/processed/sample_data.csv')

In [22]:
# df1.head(2)

In [21]:
# missing1 = df1.isnull().sum()
# missing1 = missing1[missing1 > 0].sort_values(ascending=False)

# missing_percentage1 = (missing1 / len(df1)) * 100

# print(pd.DataFrame({
#     "Missing Count": missing1,
#     "Missing %": missing_percentage1
# }).to_string())

In [20]:
# df2 = pd.read_csv('../data/processed/cleaned_data.csv')
# print(df2.head())
# missing2 = df2.isnull().sum()
# missing2 = missing2[missing2 > 0].sort_values(ascending=False)

# missing_percentage2 = (missing2 / len(df2)) * 100

# print(pd.DataFrame({
#     "Missing Count": missing2,
#     "Missing %": missing_percentage2
# }).to_string())

Split columns into 3 groups:

🟥 >40% Missing → DROP later
Too unreliable
🟨 10–40% → HANDLE carefully
Impute (median/mode)
🟩 <10% → SAFE
Minor cleaning
💡 Real Industry Insight

Banks don’t trust incomplete data.

✅ Your Output

Identify:

Top 5 columns with highest missing %
Mentally mark drop candidates

In [25]:
# def convert_target(x):
#     if x in ["Charged Off", "Default"]:
#         return 1  # Risky
#     elif x == "Fully Paid":
#         return 0  # Safe
#     else:
#         return None

# df['target1'] = df['loan_status'].apply(convert_target)

# df = df[df['target1'].notnull()]
# df.head()

In [26]:
df['target'].value_counts(normalize=True)

target
0    0.797728
1    0.202272
Name: proportion, dtype: float64

💡 Insight

👉 This is imbalanced data

Why important?

Model will try to predict everything as safe
Accuracy will be misleading
🔥 Real Fintech Thinking

Missing a defaulter = HUGE loss
So recall for class 1 matters later

In [27]:
df.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,open_acc,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,target,target1
count,59494.000000,59494.000000,59494.000000,5.949400e+04,59474.000000,59494.000000,59494.000000,59494.000000,59494.000000,59494.000000,...,56599.000000,56827.000000,59463.000000,59493.000000,5.660400e+04,5.746700e+04,57467.000000,56604.000000,59494.000000,59494.000000
mean,14398.486402,13.301648,437.650741,7.634979e+04,18.289946,0.317477,695.773103,699.773305,0.663075,11.600682,...,94.139239,45.556507,0.135462,0.054830,1.744092e+05,4.975181e+04,21461.539005,42208.596265,0.202272,0.202272
std,8736.254347,4.792188,262.506449,8.417571e+04,11.252439,0.866721,31.667783,31.668737,0.944934,5.476655,...,8.792217,36.024272,0.376834,0.492585,1.802411e+05,4.775887e+04,21242.404158,43665.534426,0.401698,0.401698
min,1000.000000,5.310000,21.740000,0.000000e+00,0.000000,0.000000,660.000000,664.000000,0.000000,1.000000,...,13.200000,0.000000,0.000000,0.000000,5.000000e+02,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,7925.000000,9.750000,248.450000,4.546625e+04,11.750000,0.000000,670.000000,674.000000,0.000000,8.000000,...,91.300000,11.100000,0.000000,0.000000,4.920875e+04,2.083350e+04,7800.000000,14667.000000,0.000000,0.000000
50%,12000.000000,12.790000,373.220000,6.500000e+04,17.660000,0.000000,690.000000,694.000000,0.000000,11.000000,...,97.900000,44.400000,0.000000,0.000000,1.120590e+05,3.721200e+04,15000.000000,31606.000000,0.000000,0.000000
75%,20000.000000,16.020000,578.360000,9.000000e+04,24.060000,0.000000,710.000000,714.000000,1.000000,14.000000,...,100.000000,75.000000,0.000000,0.000000,2.521608e+05,6.275700e+04,27900.000000,56683.000000,0.000000,0.000000
max,40000.000000,30.990000,1714.540000,1.099920e+07,999.000000,20.000000,845.000000,850.000000,7.000000,64.000000,...,100.000000,100.000000,8.000000,61.000000,9.999999e+06,1.029204e+06,296700.000000,905292.000000,1.000000,1.000000

In [29]:
df.shape

(59494, 79)

It means Total 79 columns out of which 60 are numeric columns for which describe function has calculated mean etc. For string it has not done anything.

🧠 What to Look For
1. Outliers
Very high income?
Huge loan amounts?
2. Invalid Values
Negative income?
DTI > 100?
3. Spread
Are values concentrated or wide?

In [30]:
df.groupby('target')['annual_inc'].mean()

target
0    77749.417079
1    70829.915312
Name: annual_inc, dtype: float64

In [31]:
df.groupby('target')['dti'].mean()

target
0    17.808166
1    20.190192
Name: dti, dtype: float64

In [46]:
# Analyze these columns:

# annual_inc
# dti
# loan_amnt
# int_rate
# emp_length
# home_ownership
# verification_status
# revol_util

print(df.groupby('target')['annual_inc'].mean(),"\n")
print(df.groupby('target')['dti'].mean(),"\n")
print(df.groupby('target')['loan_amnt'].mean(),"\n")
print(df.groupby('target')['int_rate'].mean(),"\n")
print(df.groupby('target')['emp_length'].apply(list),"\n")
print(df.groupby('target')['home_ownership'].apply(list),"\n")
print(df.groupby('target')['verification_status'].apply(list),"\n")
print(df.groupby('target')['revol_util'].mean(),"\n")

target
0    77749.417079
1    70829.915312
Name: annual_inc, dtype: float64

target
0    17.808166
1    20.190192
Name: dti, dtype: float64

target
0    14076.795723
1    15667.178411
Name: loan_amnt, dtype: float64

target
0    12.674815
1    15.773765
Name: int_rate, dtype: float64

target
0    [nan, 4 years, 10+ years, 10+ years, nan, 5 ye...
1    [4 years, 10+ years, 10+ years, 10+ years, 10+...
Name: emp_length, dtype: object

target
0    [RENT, MORTGAGE, RENT, MORTGAGE, RENT, RENT, R...
1    [MORTGAGE, RENT, OWN, MORTGAGE, MORTGAGE, MORT...
Name: home_ownership, dtype: object

target
0    [Verified, Not Verified, Not Verified, Not Ver...
1    [Verified, Verified, Not Verified, Not Verifie...
Name: verification_status, dtype: object

target
0    51.138281
1    55.162787
Name: revol_util, dtype: float64

In [34]:
df['target'].value_counts()

target
0    47460
1    12034
Name: count, dtype: int64

🧠 INTERVIEW GOLD (Remember This)

You should be able to say:

“I transformed loan_status into a binary target and removed ambiguous categories like current loans to ensure reliable supervised learning.”

In [35]:
df['target1'].value_counts()

target1
0    47460
1    12034
Name: count, dtype: int64

In [36]:
df['loan_status'].value_counts()

loan_status
Fully Paid     47460
Charged Off    12034
Name: count, dtype: int64

In [47]:
df.shape

(59494, 79)

## Day 2 Summary

- Created target variable
- Identified missing values
- Observed class imbalance
- Key insights:
  1. ...
  2. ...
  3. ...
  At least 3 strong insights, like:

Defaulters have higher DTI
Lower income borrowers default more
Higher interest rate → higher risk

In [48]:
df.to_csv('../data/processed/processed_stage1.csv', index=False)