In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/processed_stage3.csv")  # put correct path

df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,target,target1
0,9600.0,36,12.99,323.42,C,C1,Teacher,10,RENT,21900.0,...,0.0,11600.0,4509.0,2400.0,0.0,N,Cash,N,0,0
1,4000.0,36,6.68,122.93,A,A3,System Analyst,4,MORTGAGE,83000.0,...,0.0,222616.0,64253.0,5600.0,76154.0,N,Cash,N,0,0
2,6025.0,36,10.91,197.00,B,B4,Admin assistant,10,RENT,52000.0,...,0.0,32227.0,5559.0,11000.0,11127.0,N,Cash,N,0,0
3,20000.0,36,9.49,640.57,B,B2,Manager,10,MORTGAGE,100000.0,...,0.0,322295.0,33695.0,23900.0,29995.0,N,Cash,N,0,0
4,1600.0,36,8.18,31.42,B,B1,Teacher,10,RENT,23000.0,...,0.0,9979.0,7252.0,1700.0,5779.0,N,Cash,N,0,0

In [2]:
df.shape

(59494, 79)

Feature engineering is where you convert insights → model power.

You already KNOW:

What causes default
Which features matter

Now we encode that knowledge into new features 👇

🚀 STEP 1 — Why Feature Engineering?

Models don’t “think” like humans.

You help the model by creating:

👉 better signals from raw data

🧠 Example:

Instead of:

loan_amnt
annual_inc

👉 Create:

loan_to_income → MUCH stronger feature
🔥 STEP 2 — Create Powerful Features
💰 1. Loan-to-Income Ratio (MOST IMPORTANT)

In [3]:
df['loan_to_income'] = df['loan_amnt'] / df['annual_inc']

Meaning:

How big is the loan compared to income?

💥 Strong predictor of default

💳 2. Installment-to-Income Ratio

In [4]:
df['installment_to_income'] = df['installment'] / df['annual_inc']

🧠 Meaning:

Monthly burden relative to income

⚠️ 3. Credit Stress Score

In [5]:
df['credit_stress'] = df['dti'] * df['revol_util']

🧠 Meaning:

Combined financial pressure

📊 4. Income Buckets

In [6]:
df['income_bucket'] = pd.qcut(df['annual_inc'], q=4)

In [8]:
# pd.qcut(df['annual_inc'], q=4)

🧠 Meaning:
Low / Medium / High income groups
📊 5. DTI Buckets

In [9]:
df['dti_bucket'] = pd.cut(df['dti'], bins=[0,10,20,30,100])

In [10]:
df['int_rate_bucket'] = pd.cut(df['int_rate'], bins=[0,10,15,20,30])

🧠 Why Bucketing Helps

Models can learn:

“High DTI group = risky”
instead of exact numbers
🔥 STEP 3 — Encode Categorical Variables
🔤 Convert Categories → Numbers

In [12]:
df.columns

Index(['loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'purpose', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv',
       'last_credit_pull_d', 'last_fico_range_high', 'last_fico_range_low',
       'collections_12_mths_ex_med', 'application_type', 'acc_now_delinq',
       'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'disbursement_method',
       'debt_settlement_flag', 'target', 'target1', 'loan_to_income',
       'installment_to_income', 'credit_stress', 'income_bucket', 'dti_bucket',
       'int_rate_bucket'],
      dtype='str')

In [13]:
df.select_dtypes(include='object')

C:\Users\A\AppData\Local\Temp\ipykernel_16536\676392701.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object')

,grade,sub_grade,emp_title,home_ownership,verification_status,issue_d,loan_status,pymnt_plan,purpose,addr_state,earliest_cr_line,initial_list_status,last_credit_pull_d,application_type,hardship_flag,disbursement_method,debt_settlement_flag
0,C,C1,Teacher,RENT,Verified,2014-05-01,Fully Paid,n,debt_consolidation,FL,2001-04-01,w,2017-08-01,Individual,N,Cash,N
1,A,A3,System Analyst,MORTGAGE,Not Verified,2015-04-01,Fully Paid,n,major_purchase,FL,2003-09-01,w,2019-02-01,Individual,N,Cash,N
2,B,B4,Admin assistant,RENT,Not Verified,2017-12-01,Fully Paid,n,debt_consolidation,MA,2005-06-01,w,2018-10-01,Individual,N,Cash,N
3,B,B2,Manager,MORTGAGE,Not Verified,2016-08-01,Fully Paid,n,debt_consolidation,NV,1990-08-01,w,2019-03-01,Individual,N,Cash,N
4,B,B1,Teacher,RENT,Verified,2015-04-01,Fully Paid,n,debt_consolidation,OH,1986-09-01,w,2018-05-01,Individual,N,Cash,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59489,A,A1,Engineer,RENT,Not Verified,2014-08-01,Fully Paid,n,debt_consolidation,WI,2000-05-01,w,2019-03-01,Individual,N,Cash,N
59490,B,B3,Supervisor,MORTGAGE,Not Verified,2015-12-01,Fully Paid,n,home_improvement,CA,1996-02-01,f,2018-12-01,Individual,N,Cash,N
59491,D,D3,CEO,RENT,Source Verified,2015-03-01,Fully Paid,n,debt_consolidation,MO,1993-04-01,f,2018-04-01,Individual,N,Cash,N
59492,C,C2,Austin Independent School District,MORTGAGE,Verified,2012-09-01,Fully Paid,n,debt_consolidation,TX,2002-09-01,f,2015-08-01,Individual,N,Cash,N
59493,A,A2,Locomotive Engineer,MORTGAGE,Not Verified,2015-03-01,Fully Paid,n,credit_card,OK,2002-08-01,w,2019-03-01,Individual,N,Cash,N

🧠 Why?

ML models only understand numbers

⚠️ Important:

Before encoding:

Remove useless columns like:
emp_title
IDs
🚀 STEP 4 — Feature Selection (Light)

Drop:

Irrelevant
Redundant

Keep:

All important + engineered features
🔥 STEP 5 — Check Final Dataset

In [11]:
print(df.shape)
df.head()

(59494, 85)

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,disbursement_method,debt_settlement_flag,target,target1,loan_to_income,installment_to_income,credit_stress,income_bucket,dti_bucket,int_rate_bucket
0,9600.0,36,12.99,323.42,C,C1,Teacher,10,RENT,21900.0,...,Cash,N,0,0,0.438356,0.014768,390.167,"(17999.999, 45466.25]","(10, 20]","(10, 15]"
1,4000.0,36,6.68,122.93,A,A3,System Analyst,4,MORTGAGE,83000.0,...,Cash,N,0,0,0.048193,0.001481,335.916,"(65000.0, 90000.0]","(10, 20]","(0, 10]"
2,6025.0,36,10.91,197.00,B,B4,Admin assistant,10,RENT,52000.0,...,Cash,N,0,0,0.115865,0.003788,117.248,"(45466.25, 65000.0]","(0, 10]","(10, 15]"
3,20000.0,36,9.49,640.57,B,B2,Manager,10,MORTGAGE,100000.0,...,Cash,N,0,0,0.200000,0.006406,925.009,"(90000.0, 250000.0]","(10, 20]","(0, 10]"
4,1600.0,36,8.18,31.42,B,B1,Teacher,10,RENT,23000.0,...,Cash,N,0,0,0.069565,0.001366,1259.814,"(17999.999, 45466.25]","(10, 20]","(0, 10]"

In [ ]:
# 🧠 Golden Rule Before Encoding

# 👉 Keep columns that:

# Add predictive value
# Are available at loan approval time

# 👉 Drop columns that:

# Cause data leakage
# Are too messy / high-cardinality
# Are post-loan information
# 🚨 DROP THESE (VERY IMPORTANT)

# These will hurt your model or leak future info 👇

# ❌ 1. Direct Leakage Columns
# loan_status ❌ (you already created target from this)

# 👉 Drop immediately

# ❌ 2. Post-Loan Information (BIG NO)

# These are created after loan is issued:

# last_credit_pull_d ❌
# issue_d ❌
# pymnt_plan ❌
# debt_settlement_flag ❌
# hardship_flag ❌

# 👉 These leak future behavior

# ❌ 3. High Cardinality / Useless Text
# emp_title ❌ (too many unique values)

# 👉 Adds noise, not value

# ❌ 4. Redundant / Already Processed
# earliest_cr_line ❌ (you already converted to credit_age)
# ⚠️ CONSIDER DROPPING (OPTIONAL BUT RECOMMENDED)
# ⚠️ sub_grade
# Too granular
# Already covered by grade

# 👉 Keep ONE:

# ✅ Keep grade
# ❌ Drop sub_grade
# ✅ KEEP THESE (IMPORTANT FEATURES)

# These are valuable 👇

# 🏠 Stability
# home_ownership ✅
# 🧾 Risk Assessment
# grade ✅
# verification_status ✅
# 💳 Loan Intent
# purpose ✅
# 🌍 Location (Optional but useful)
# addr_state ✅
# 🏦 Loan Setup
# initial_list_status ✅
# application_type ✅
# disbursement_method ✅
# ⚠️ Special Case
# issue_d

# 👉 If you want:

# Extract year/month → keep transformed version
# Otherwise → drop

# 🧾 What You Should Write (IMPORTANT)

“Feature engineering was performed by creating ratio-based features such as loan-to-income and installment-to-income, along with bucketed variables to capture non-linear relationships and improve model interpretability.”

💥 Interview gold

🧠 What You Just Did

You transformed:

Raw data → intelligent signals

👉 This is what makes models powerful

In [14]:

drop_cols = [
    'loan_status',
    'emp_title',
    'pymnt_plan',
    'last_credit_pull_d',
    'earliest_cr_line',
    'hardship_flag',
    'debt_settlement_flag'
]

In [15]:
df = df.drop(columns=drop_cols)

🧾 Interview Answer

“I removed high-cardinality, redundant, and post-loan variables to prevent data leakage and ensure the model only uses information available at decision time.”

In [16]:
df = pd.get_dummies(df, drop_first=True)

In [17]:
print(df.shape)
df.head()

(59494, 322)

,loan_amnt,term,int_rate,installment,emp_length,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,...,disbursement_method_DirectPay,"income_bucket_(45466.25, 65000.0]","income_bucket_(65000.0, 90000.0]","income_bucket_(90000.0, 250000.0]","dti_bucket_(10, 20]","dti_bucket_(20, 30]","dti_bucket_(30, 100]","int_rate_bucket_(10, 15]","int_rate_bucket_(15, 20]","int_rate_bucket_(20, 30]"
0,9600.0,36,12.99,323.42,10,21900.0,10.03,0.0,685.0,689.0,...,False,False,False,False,True,False,False,True,False,False
1,4000.0,36,6.68,122.93,4,83000.0,19.53,0.0,780.0,784.0,...,False,False,True,False,True,False,False,False,False,False
2,6025.0,36,10.91,197.00,10,52000.0,9.16,1.0,740.0,744.0,...,False,True,False,False,False,False,False,True,False,False
3,20000.0,36,9.49,640.57,10,100000.0,16.43,1.0,695.0,699.0,...,False,False,False,True,True,False,False,False,False,False
4,1600.0,36,8.18,31.42,10,23000.0,16.34,1.0,680.0,684.0,...,False,False,False,False,True,False,False,False,False,False

In [18]:
df.select_dtypes(include='object').columns

Index([], dtype='str')

In [19]:
df.to_csv("../data/processed/processed_stage4.csv", index=False)